# Exercise
Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest

In [29]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [30]:
iris = load_iris()

# Logistic regression

In [34]:
l_score = cross_val_score(LogisticRegression(max_iter=150), iris.data, iris.target)
l_score

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [35]:
np.average(l_score)

np.float64(0.9733333333333334)

# Decision Tree

In [36]:
d_score = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [37]:
np.average(d_score)

np.float64(0.9666666666666668)

# SVM 

In [38]:
s_score = cross_val_score(SVC(), iris.data, iris.target)
s_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [39]:
np.average(s_score)

np.float64(0.9666666666666666)

# Random Forest

In [40]:
rf_score = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [41]:
np.average(rf_score)

np.float64(0.96)